---
- hosts: all #localhost
  gather_facts: true
  become: true
  tasks:
    - name: add mysql .deb package
      apt:
        deb: https://dev.mysql.com/get/mysql-apt-config_0.8.17-1_all.deb

    - name: Install mysql-server
      apt:
        update_cache: true
        name: mysql-server
        state: present

    - name: Enable mysql service
      service:
        name: mysql
        enabled: true
